image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      export EDITOR="command gp open -w" VISUAL="command gp open -w"
      cp -f /workspace/coffeezhs/templates/zshrc.zsh-template ~/.zshrc
      ln -sf /workspace/coffeezhs ~/.oh-my-zsh
    command: exec zsh
